common: &common
  hostname: https://winesimple-ecom.cloudant.com/database
  port: 8091
  username: andentoperadingeressinsi
  password: V1BjVRv73b1P071ckie64Hgv
  pool: default

development:
  <<: *common
  # bucket: ecom_transaction_server_development

test:
  <<: *common
  # bucket: ecom_transaction_server_test

# set these environment variables on your production server
production:
  hostname: <%= ENV['COUCHBASE_HOST'] %>
  port: <%= ENV['COUCHBASE_PORT'] %>
  username: <%= ENV['COUCHBASE_USERNAME'] %>
  password: <%= ENV['COUCHBASE_PASSWORD'] %>
  pool: <%= ENV['COUCHBASE_POOL'] %>
  bucket: <%= ENV['COUCHBASE_BUCKET'] %>
